---
title: "Cookie Problem"
author: "Madeleine Snow"
date: "10/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(janitor)
library(fs)

```

```{r tibble, include=FALSE}

bowls <- tibble(replicate = 1:10000) %>% 
       mutate(which_bowl = sample(c("Bowl 1", "Bowl 2"), size = 10000, replace = TRUE)) %>% 
       mutate(cookie = ifelse(which_bowl == "Bowl 1", 
          sample(c("vanilla", "chocolate"), size = 10000, replace = TRUE, prob = c(0.75, 0.25)),
          sample(c("vanilla", "chocolate"), size = 10000, replace = TRUE, prob = c(0.5, 0.5))))
       
```

```{r vanilla, include=FALSE}

# if you pick a vanilla cookie, what is the probability that it is from bowl 1 or bowl 2?

bowls %>% 
  tabyl(which_bowl, cookie) %>% 
  adorn_percentages(denominator = "col") %>% 
  adorn_pct_formatting()

```


```{govdata, include=FALSE}

download.file(https://docs.google.com/spreadsheets/d/e/2PACX-1vSaerGnn1tDQfgiyJRl7jnn1Au7Ev6Qt7BwMpl53ZgzAyMnANQfog9y4es4ZExlX5tjEgl0mPIyTGcP/pub?gid=480043959&single=true&output=csv, destfile = "trains.csv")

trains <- read_csv("trains.csv")

trains %>% 
  group_by(treatment) %>% 
  summarise(avg = mean(attitude))

```

